# tasks/main.yml
#
# Define server related common tasks

---
- name: Setup some basic environment vars
  copy:
    src: environment.sh
    dest: /etc/profile.d/environment.sh

- name: Ensure packages are installed
  apt:
    name: "{{ all_packages }}"
    state: present

- name: Modify hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups.all }}"

- name: Ensure hostname is set correctly
  hostname:
    name:  "{{ inventory_hostname }}"

- name: Ensure correct timezone is configured 
  timezone: 
    name: "{{ timezone }}"






